### ISSUE TITLE
Lydia AI Responds to bots

### ISSUE THREAD

**Issue by Netkas** [penn5/friendly-telegram#6]
There is an issue where when Lydia AI would respond to bots as if they were users and this usually leads to spam between the two bots.

**Comment by penn5** [comment]
@Netkas I did that on purpose, I like talking to lydia

**Comment by Netkas** [comment]
@penn5 it's a bit annoying whenever you start a bot and Lydia starts spamming the bot with responses before you can even disable it.

**Comment by Netkas** [comment]
@penn5 (Actual bots) not userbots.

**Comment by penn5** [comment]
@Netkas Meeeeeh, if you're so worried, pr it

**Comment by AzzyC** [comment]
@penn5 hi guys, felt cute might delete later

**Comment by Netkas** [comment]
@penn5 ...

**Comment by Netkas** [comment]
@penn5 A lot of sessions that get created often has more than 1k requests which consists of a bot spamming the userbot. this puts a load on our end which I feel is unnecessary. to prevent this I have to limit some access keys to 1,000 requests monthly. but that's the best I can do to combat the problem

**Comment by Netkas** [comment]
For any session that spams a bunch of requests will be limited to 1,000 monthly requests, they can appeal for this but that's the best I can do considering the lack of support from your side.

**Comment by penn5** [comment]
This is an issue. Just I cant fix it this week.

**Comment by penn5** [comment]
Oh my earlier message was didn't send. 

I agree that we should disable autoreply for bots, but I can't do anything this week or next as I'm on holiday
